name: vItems
version: "1.0.0"
main: com.vallerinsmp.vitems.VItems
author: mtynnn
api-version: "1.21"
softdepend: [WorldGuard]

commands:
  vitems:
    description: vItems main command
    usage: /<command> [give|reload|list]
    aliases: [vi, vitem]
